/*
 * WardCronograma — o cronograma padrao da Ward Academy (fonte unica).
 *
 * São 185 blocos, 3.641 questoes no total, na ordem em que o aluno estuda.
 * Gerado a partir da planilha CRONOGRAMA_SUBJECT_SYSTEM.xlsx: para mudar o
 * cronograma padrao, mude aqui — e so daqui que a pagina do Marcos carrega.
 *
 * `aulas` é o texto de aulas recomendadas que vai junto de cada bloco.
 * As datas nao ficam aqui: elas saem do gerador, a partir das datas de inicio e
 * de prova de cada aluno.
 */
(function () {
    'use strict';

    var PADRAO = [
        { system: 'Cardiovascular System', subject: 'Pathology', questions: 99, aulas: 'B&B: Atherosclerosis • Cardiac Ischemia • STEMI • Unstable Angina/NSTEMI • Heart Failure Basics • Pericardial Disease • Hypertrophic Cardiomyopathy • Valve Disease • Endocarditis | Pathoma: 3.1 Neoplasia' },
        { system: 'Cardiovascular System', subject: 'Pathophysiology', questions: 97, aulas: 'B&B: Heart Failure Basics • Systolic and Diastolic Heart Failure • Shock • Cardiac Ischemia • Hypertension • Secondary Hypertension • Aortic Dissection • Starling Curve' },
        { system: 'Cardiovascular System', subject: 'Pharmacology', questions: 91, aulas: 'Sketchy Pharm: Statins • Antiplatelet agents • Class I A-C • Class II • Class III • Class IV • Class V • Digoxin • Heparin, LMWH, fondaparinux • Nitrates • Beta blockers • ACE inhibitors, ARBs, Aliskiren • Loop diuretics • Thiazides • K+ sparing diuretics • Calcium channel blockers • Warfarin • Alpha drugs' },
        { system: 'Cardiovascular System', subject: 'Physiology', questions: 75, aulas: 'B&B: Cardiac Physiology • CV Response to Exercise • Blood Flow Mechanics • Regulation of Blood Pressure • PV Loops • Wiggers Diagram • Venous Pressure Tracings • Starling Curve • Cardiac Muscle • Cardiac Action Potentials' },
        { system: 'Cardiovascular System', subject: 'Anatomy', questions: 34, aulas: 'B&B: Cardiac Anatomy • EKG Basics • High Yield EKGs • Heart Sounds • Heart Murmurs' },
        { system: 'Cardiovascular System', subject: 'Embryology', questions: 7, aulas: 'B&B: Cardiac Embryology • Shunts • Cyanotic Congenital Heart Disease • Coarctation of the Aorta' },
        { system: 'Cardiovascular System', subject: 'Genetics', questions: 4, aulas: 'B&B: Cardiac Embryology • Hypertrophic Cardiomyopathy' },
        { system: 'Cardiovascular System', subject: 'Biochemistry', questions: 2, aulas: 'B&B: Atherosclerosis | Dirty Medicine: Lipid Transport' },
        { system: 'Cardiovascular System', subject: 'Histology', questions: 2, aulas: 'B&B: Cardiac Muscle' },
        { system: 'Cardiovascular System', subject: 'Immunology', questions: 1, aulas: 'B&B: Pericardial Disease | Pathoma: 2.4 Autoimmune Disorders' },
        { system: 'Cardiovascular System', subject: 'Microbiology', questions: 1, aulas: 'Sketchy Micro: Staphylococcus aureus • Streptococcus viridans • Enterococcus' },
        { system: 'Renal, Urinary Systems & Electrolytes', subject: 'Pathology', questions: 87, aulas: 'B&B: Renal Failure • Tubulointerstitial Disease • Glomerulonephritis Principles • Nephritic Syndrome • Nephrotic Syndrome • MPGN • Renal and Bladder Tumors • Cystic Kidney Disease | Pathoma: 2.4 Autoimmune Disorders • 3.1 Neoplasia • 3.2 Carcinogenesis' },
        { system: 'Renal, Urinary Systems & Electrolytes', subject: 'Physiology', questions: 45, aulas: 'B&B: Renal Physiology I • Renal Physiology II • Nephron Physiology • Renal Endocrinology • Acid Excretion • Acid-Base Principles • Sodium and Water Balance' },
        { system: 'Renal, Urinary Systems & Electrolytes', subject: 'Pharmacology', questions: 35, aulas: 'Sketchy Pharm: Loop diuretics • Thiazides • K+ sparing diuretics • Acetazolamide, mannitol • ACE inhibitors, ARBs, Aliskiren • Glucocorticoids • Immunosuppressants • Bisphosphonates, raloxifene, denosumab, calcitonin • Teriparatide, vitamin D, cinacalcet, sevelamer • ADH, DDAVP, ADH receptor antagonists • Muscarinic antagonists • Cholinomimetics' },
        { system: 'Renal, Urinary Systems & Electrolytes', subject: 'Pathophysiology', questions: 30, aulas: 'B&B: Renal Failure • Acid-Base Principles • Respiratory Acid-Base Disorders • Metabolic Alkalosis • Renal Tubular Acidosis • Metabolic Acidosis • Electrolyte Disorders • Sodium Disorders • Rhabdomyolysis' },
        { system: 'Renal, Urinary Systems & Electrolytes', subject: 'Embryology', questions: 10, aulas: 'B&B: Renal Embryology • Cystic Kidney Disease' },
        { system: 'Renal, Urinary Systems & Electrolytes', subject: 'Anatomy', questions: 9, aulas: 'B&B: Renal Anatomy' },
        { system: 'Renal, Urinary Systems & Electrolytes', subject: 'Histology', questions: 3, aulas: 'B&B: Nephron Physiology' },
        { system: 'Renal, Urinary Systems & Electrolytes', subject: 'Biochemistry', questions: 2, aulas: 'B&B: Acid-Base Principles • Electrolyte Disorders' },
        { system: 'Renal, Urinary Systems & Electrolytes', subject: 'Immunology', questions: 2, aulas: 'B&B: Glomerulonephritis Principles | Pathoma: 2.4 Autoimmune Disorders Part 1 • 2.4 Autoimmune Disorders Part 2' },
        { system: 'Renal, Urinary Systems & Electrolytes', subject: 'Genetics', questions: 1, aulas: 'B&B: Cystic Kidney Disease' },
        { system: 'Pulmonary & Critical Care', subject: 'Pathophysiology', questions: 79, aulas: 'B&B: Shock • Hypoxia • Ventilation and Perfusion • Carbon Dioxide • Obstructive Lung Disease • Restrictive Lung Disease • Pulmonary Function Tests • Pulmonary Embolism' },
        { system: 'Pulmonary & Critical Care', subject: 'Pathology', questions: 60, aulas: 'B&B: Obstructive Lung Disease • Restrictive Lung Disease • Sarcoidosis • Lung Cancer • Cystic Fibrosis | Pathoma: 2.2 Chronic Inflammation • 3.1 Neoplasia • 3.2 Carcinogenesis • 3.3 Tumor Progression • 3.4 Clinical Characteristics' },
        { system: 'Pulmonary & Critical Care', subject: 'Microbiology', questions: 42, aulas: 'Sketchy Micro: Streptococcus pneumoniae • Haemophilus influenzae • Legionella pneumophila • Mycobacterium tuberculosis • Pseudomonas aeruginosa • Klebsiella pneumoniae • Mycoplasma pneumoniae • Histoplasma • Blastomyces • Coccidioides • Aspergillus • Pneumocystis jirovecii' },
        { system: 'Pulmonary & Critical Care', subject: 'Physiology', questions: 36, aulas: 'B&B: Pulmonary Physiology • Hemoglobin • Pulmonary Circulation • Ventilation and Perfusion • Carbon Dioxide • Pulmonary Physical Exam' },
        { system: 'Pulmonary & Critical Care', subject: 'Pharmacology', questions: 21, aulas: 'Sketchy Pharm: Asthma therapy • Glucocorticoids • Sympathomimetics • Heparin, LMWH, fondaparinux • Warfarin • Thrombolytics • Prostaglandins, prostacyclin, bosentan, PDE5 inhibitors • Penicillin • Cephalosporins • Macrolides • Fluoroquinolones • Tuberculosis Drugs • Nonbenzodiazepine hypnotics, melatonin, ramelteon • Armodafinil & Modafinil' },
        { system: 'Pulmonary & Critical Care', subject: 'Anatomy', questions: 8, aulas: 'B&B: Pulmonary Anatomy • Pulmonary Physical Exam' },
        { system: 'Pulmonary & Critical Care', subject: 'Immunology', questions: 7, aulas: 'B&B: Sarcoidosis | Pathoma: 2.2 Chronic Inflammation' },
        { system: 'Pulmonary & Critical Care', subject: 'Biochemistry', questions: 4, aulas: 'B&B: Hemoglobin • Carbon Dioxide' },
        { system: 'Pulmonary & Critical Care', subject: 'Embryology', questions: 3, aulas: 'B&B: Pulmonary Embryology' },
        { system: 'Pulmonary & Critical Care', subject: 'Histology', questions: 3, aulas: 'B&B: Pulmonary Anatomy' },
        { system: 'Pulmonary & Critical Care', subject: 'Genetics', questions: 2, aulas: 'B&B: Cystic Fibrosis' },
        { system: 'Gastrointestinal & Nutrition', subject: 'Pathology', questions: 123, aulas: 'B&B: Esophageal Disorders • Gastric Disorders • Liver Disease • Cirrhosis • Liver Tumors • Intestinal Disorders • Inflammatory Bowel Disease • Colon Cancer • Gallstones • Biliary Disorders • Acute Pancreatitis • Chronic Pancreatitis & Pancreatic Cancer | Pathoma: 3.1 Neoplasia • 3.2 Carcinogenesis • 3.3 Tumor Progression' },
        { system: 'Gastrointestinal & Nutrition', subject: 'Pathophysiology', questions: 44, aulas: 'B&B: Esophageal Disorders • Gastric Disorders • Liver Disease • Cirrhosis • Malabsorption • Inflammatory Bowel Disease • Acute Pancreatitis' },
        { system: 'Gastrointestinal & Nutrition', subject: 'Anatomy', questions: 38, aulas: 'B&B: Gastrointestinal Anatomy • Gastrointestinal Blood Supply • Liver, Gallbladder, and Pancreas • Hernias' },
        { system: 'Gastrointestinal & Nutrition', subject: 'Pharmacology', questions: 28, aulas: 'Sketchy Pharm: H2 receptor blockers, PPIs • Antiemetic agents • Laxatives • Antidiarrheals • Glucocorticoids • TNF Inhibitors' },
        { system: 'Gastrointestinal & Nutrition', subject: 'Embryology', questions: 18, aulas: 'B&B: Gastrointestinal Embryology' },
        { system: 'Gastrointestinal & Nutrition', subject: 'Microbiology', questions: 18, aulas: 'Sketchy Micro: Helicobacter pylori • Hepatitis A virus • Hepatitis B virus • Hepatitis C virus • Salmonella • Shigella • Campylobacter jejuni • E. coli ETEC EHEC • Clostridioides Difficile • Giardia lamblia • Entamoeba histolytica' },
        { system: 'Gastrointestinal & Nutrition', subject: 'Physiology', questions: 18, aulas: 'B&B: Gastrointestinal Tract • Salivary Glands • Bile • Bilirubin • Gastrointestinal Secretions • Gastrointestinal Hormones • Exocrine Pancreas' },
        { system: 'Gastrointestinal & Nutrition', subject: 'Biochemistry', questions: 13, aulas: 'B&B: Malabsorption • B Vitamins • B12 and Folate • Other Vitamins • Wilson\'s Disease and Hemochromatosis • Bilirubin | Dirty Medicine: Fat Soluble Vitamins • Metabolic Fuel & Starvation • High Yield Alcohol • Alcohol Metabolism' },
        { system: 'Gastrointestinal & Nutrition', subject: 'Histology', questions: 3, aulas: 'B&B: Gastrointestinal Tract' },
        { system: 'Gastrointestinal & Nutrition', subject: 'Behavioral science', questions: 1, aulas: 'Dirty Medicine: High Yield Alcohol' },
        { system: 'Gastrointestinal & Nutrition', subject: 'Genetics', questions: 1, aulas: 'B&B: Wilson\'s Disease and Hemochromatosis' },
        { system: 'Gastrointestinal & Nutrition', subject: 'Immunology', questions: 1, aulas: 'B&B: Inflammatory Bowel Disease | Pathoma: 2.2 Chronic Inflammation' },
        { system: 'Endocrine, Diabetes & Metabolism', subject: 'Pathophysiology', questions: 51, aulas: 'B&B: Type I Diabetes • Type II Diabetes • Hyperthyroidism • Hypothyroidism and Thyroiditis • Adrenal Insufficiency • Cushing Syndrome • Hyperaldosteronism • Hyperlipidemia' },
        { system: 'Endocrine, Diabetes & Metabolism', subject: 'Pharmacology', questions: 51, aulas: 'Sketchy Pharm: Insulin, sulfonylureas, meglitinides, GLP-1 agonists, DPP-4 inhibitors • Metformin, thiazolidinediones, pramlintide, SGLT2 inhibitors • Propylthiouracil, methimazole, levothyroxine • Glucocorticoids • Growth hormone, mecasermin, octreotide, pegvisomant • ADH, DDAVP, ADH receptor antagonists • SERMs & Aromatase Inhibitors • LHRH agonists/GnRH analogs • Statins • Cholestyramine, ezetimibe • Fibrates, niacin • PCSK9 inhibitors' },
        { system: 'Endocrine, Diabetes & Metabolism', subject: 'Physiology', questions: 35, aulas: 'B&B: Signalling Pathways • Thyroid Anatomy & Physiology • Thyroid Hormone Synthesis & Labs • Adrenal Glands • Pituitary Anatomy and Physiology • Insulin • Glucagon & Hypoglycemia • Female Reproductive Hormones • Male Reproductive Hormones • Menstrual Cycle | Dirty Medicine: Signal Transduction Pathways' },
        { system: 'Endocrine, Diabetes & Metabolism', subject: 'Pathology', questions: 31, aulas: 'B&B: MEN Syndromes • Pituitary Pathology • Adrenal Tumors • Thyroid Cancer • Type I Diabetes • Type II Diabetes | Pathoma: 3.1 Neoplasia' },
        { system: 'Endocrine, Diabetes & Metabolism', subject: 'Biochemistry', questions: 23, aulas: 'B&B: Lipid Metabolism • Hyperlipidemia • Lipid Drugs | Dirty Medicine: Lipid Transport (pt. 1) • Lipid Transport (pt. 2) • Lipid Transport (Pt. 3) • Familial Dyslipidemias • Signal Transduction Pathways' },
        { system: 'Endocrine, Diabetes & Metabolism', subject: 'Embryology', questions: 3, aulas: 'B&B: Congenital Adrenal Hyperplasia' },
        { system: 'Endocrine, Diabetes & Metabolism', subject: 'Anatomy', questions: 2, aulas: 'B&B: Thyroid Anatomy & Physiology • Adrenal Glands • Pituitary Anatomy and Physiology' },
        { system: 'Endocrine, Diabetes & Metabolism', subject: 'Biostatistics', questions: 1, aulas: 'B&B: Clinical Trials' },
        { system: 'Endocrine, Diabetes & Metabolism', subject: 'Genetics', questions: 1, aulas: 'B&B: MEN Syndromes • Congenital Adrenal Hyperplasia' },
        { system: 'Endocrine, Diabetes & Metabolism', subject: 'Histology', questions: 1, aulas: 'B&B: Thyroid Anatomy & Physiology' },
        { system: 'Male Reproductive System', subject: 'Pathology', questions: 12, aulas: 'B&B: Penile Disorders • Scrotal Disorders • Testicular Cancer • Prostate' },
        { system: 'Male Reproductive System', subject: 'Anatomy', questions: 10, aulas: 'B&B: Male Reproductive Hormones • Prostate' },
        { system: 'Male Reproductive System', subject: 'Pharmacology', questions: 10, aulas: 'Sketchy Pharm: Non-steroidal Antiandrogens • PDE5 inhibitors' },
        { system: 'Male Reproductive System', subject: 'Physiology', questions: 6, aulas: 'B&B: Male Reproductive Hormones • Spermatogenesis and Oogenesis' },
        { system: 'Male Reproductive System', subject: 'Embryology', questions: 4, aulas: 'B&B: Genital Embryology • Disorders of Sexual Development' },
        { system: 'Male Reproductive System', subject: 'Behavioral science', questions: 3, aulas: 'B&B: Hypogonadism' },
        { system: 'Male Reproductive System', subject: 'Genetics', questions: 2, aulas: 'B&B: Disorders of Sexual Development' },
        { system: 'Male Reproductive System', subject: 'Microbiology', questions: 2, aulas: 'Sketchy Micro: Neisseria gonorrhoeae • Chlamydia trachomatis' },
        { system: 'Male Reproductive System', subject: 'Pathophysiology', questions: 2, aulas: 'B&B: Hypogonadism • Prostate' },
        { system: 'Male Reproductive System', subject: 'Histology', questions: 1, aulas: 'B&B: Spermatogenesis and Oogenesis' },
        { system: 'Female Reproductive System & Breast', subject: 'Pathology', questions: 21, aulas: 'B&B: Breast Disorders • Breast Carcinoma • Vaginal Cancer • Cervical Cancer • Endometrial Disorders • Endometrial Cancer • Ovarian Cysts • Ovarian Epithelial Tumors • Ovarian Stromal Tumors • Ovarian Germ Cell Tumors | Pathoma: 3.1 Neoplasia • 3.2 Carcinogenesis' },
        { system: 'Female Reproductive System & Breast', subject: 'Anatomy', questions: 14, aulas: 'B&B: Breast Tissue • Genital Embryology' },
        { system: 'Female Reproductive System & Breast', subject: 'Pathophysiology', questions: 11, aulas: 'B&B: Endometrial Disorders • Primary Amenorrhea • Secondary Amenorrhea • Endometriosis' },
        { system: 'Female Reproductive System & Breast', subject: 'Microbiology', questions: 8, aulas: 'Sketchy Micro: E. coli • Chlamydia trachomatis • Neisseria gonorrhoeae • Treponema pallidum • Gardnerella vaginalis • Trichomonas Vaginalis • Candida albicans • Human papillomavirus' },
        { system: 'Female Reproductive System & Breast', subject: 'Genetics', questions: 7, aulas: 'B&B: Disorders of Sexual Development | Pathoma: 3.2 Carcinogenesis' },
        { system: 'Female Reproductive System & Breast', subject: 'Physiology', questions: 6, aulas: 'B&B: Spermatogenesis and Oogenesis • Female Reproductive Hormones • Menstrual Cycle' },
        { system: 'Female Reproductive System & Breast', subject: 'Histology', questions: 4, aulas: 'B&B: Breast Tissue' },
        { system: 'Female Reproductive System & Breast', subject: 'Pharmacology', questions: 4, aulas: 'Sketchy Pharm: SERMs & Aromatase Inhibitors • Trimethoprim/sulfamethoxazole • Fluoroquinolones' },
        { system: 'Female Reproductive System & Breast', subject: 'Behavioral science', questions: 2, aulas: 'B&B: Menstrual Cycle • Contraceptives' },
        { system: 'Female Reproductive System & Breast', subject: 'Embryology', questions: 2, aulas: 'B&B: Genital Embryology • Disorders of Sexual Development' },
        { system: 'Pregnancy, Childbirth & Puerperium', subject: 'Pathophysiology', questions: 21, aulas: 'B&B: Maternal-Fetal Disorders • Hypertension in Pregnancy • Placental Complications • Gestational Tumors' },
        { system: 'Pregnancy, Childbirth & Puerperium', subject: 'Physiology', questions: 8, aulas: 'B&B: Placenta • Twins • Pregnancy • Spermatogenesis and Oogenesis' },
        { system: 'Pregnancy, Childbirth & Puerperium', subject: 'Pathology', questions: 7, aulas: 'B&B: Gestational Tumors • Placental Complications' },
        { system: 'Pregnancy, Childbirth & Puerperium', subject: 'Pharmacology', questions: 7, aulas: 'B&B: TORCH Infections | Sketchy Pharm: (teratogenic drugs awareness)' },
        { system: 'Pregnancy, Childbirth & Puerperium', subject: 'Embryology', questions: 6, aulas: 'B&B: Placenta • Twins' },
        { system: 'Pregnancy, Childbirth & Puerperium', subject: 'Anatomy', questions: 3, aulas: 'B&B: Placenta' },
        { system: 'Pregnancy, Childbirth & Puerperium', subject: 'Genetics', questions: 3, aulas: 'B&B: Maternal-Fetal Disorders' },
        { system: 'Pregnancy, Childbirth & Puerperium', subject: 'Microbiology', questions: 3, aulas: 'Sketchy Micro: Toxoplasma gondii • Rubella virus • Cytomegalovirus • Herpes simplex virus • Treponema pallidum • Listeria monocytogenes • Streptococcus agalactiae' },
        { system: 'Pregnancy, Childbirth & Puerperium', subject: 'Histology', questions: 1, aulas: 'B&B: Placenta' },
        { system: 'Psychiatric/Behavioral & Substance Use Disorder', subject: 'Behavioral science', questions: 139, aulas: 'B&B: Conditioning and Transference • Ego Defenses • The Healthy Patient • Pediatrics • Anxiety Disorders • Mood Disorders • Childhood Disorders • ADHD and Autism • Personality Disorders • Psychosis • Psychotic Disorders • Eating Disorders • Somatic and Factitious Disorders • Alcohol and CNS Depressants • Opioids • Stimulants • Other Drugs | Dirty Medicine: Core Ethical Principles • Patient Centered Care' },
        { system: 'Psychiatric/Behavioral & Substance Use Disorder', subject: 'Pharmacology', questions: 35, aulas: 'Sketchy Pharm: SSRIs, SNRIs, cyproheptadine • Benzodiazepines, flumazenil • Buspirone • Tricyclic antidepressants • MAO inhibitors • Bupropion, mirtazapine, trazodone • Lithium • Amphetamine, Methylphenidate • First generation antipsychotics • Second generation antipsychotics • Opioids, naloxone, naltrexone • Varenicline' },
        { system: 'Psychiatric/Behavioral & Substance Use Disorder', subject: 'Pathophysiology', questions: 3, aulas: 'B&B: Mood Disorders • Psychosis | Dirty Medicine: High Yield Alcohol • Alcohol Metabolism' },
        { system: 'Psychiatric/Behavioral & Substance Use Disorder', subject: 'Anatomy', questions: 1, aulas: 'B&B: Thalamus, Hypothalamus, Limbic System' },
        { system: 'Psychiatric/Behavioral & Substance Use Disorder', subject: 'Biochemistry', questions: 1, aulas: 'B&B: Neurotransmitters | Dirty Medicine: Alcohol Metabolism' },
        { system: 'Social Sciences (Ethics/Legal/Professional)', subject: 'Behavioral science', questions: 106, aulas: 'B&B: Ethics Principles • Informed Consent • Confidentiality • Decision-Making Capacity • Quality and Safety • Public Health | Dirty Medicine: Core Ethical Principles (Part 1) • Core Ethical Principles (Part 2) • Informed Consent • Patient Centered Care • Stages of Change • Capacity vs. Competency • EMTALA Laws • Emancipated Minors • Consent vs. Assent • Next of Kin, Living Wills • Confidentiality (HIPAA) • Medical Malpractice • Insurance (Medicare, Medicaid, COBRA) • Healthcare Fraud & Abuse • Patient Safety & Quality Improvement' },
        { system: 'Social Sciences (Ethics/Legal/Professional)', subject: 'Biostatistics', questions: 1, aulas: 'B&B: Public Health' },
        { system: 'Social Sciences (Ethics/Legal/Professional)', subject: 'Immunology', questions: 1, aulas: 'B&B: Public Health' },
        { system: 'Nervous System', subject: 'Anatomy', questions: 119, aulas: 'B&B: Cells of the Nervous System • Dermatomes and Reflexes • Cerebral Cortex • Spinal Cord • Brainstem • Cranial Nerves • Thalamus, Hypothalamus, Limbic System • Cerebellum • Basal Ganglia • Ventricles and Sinuses • Autonomic Nervous System • Brachial Plexus • Lumbosacral Plexus' },
        { system: 'Nervous System', subject: 'Pathology', questions: 118, aulas: 'B&B: Cerebral and Lacunar Strokes • Vertebrobasilar Stroke Syndromes • CNS Aneurysms • Intracranial Bleeding • Meningitis • Demyelinating Diseases • Delirium and Dementia • Parkinson\'s, Huntington\'s, and Movement Disorders • Brain Tumors • Spinal Cord Syndromes | Pathoma: 3.1 Neoplasia' },
        { system: 'Nervous System', subject: 'Pharmacology', questions: 55, aulas: 'Sketchy Pharm: Antiplatelet agents • Thrombolytics • Heparin, LMWH, fondaparinux • Warfarin • Penicillin • Cephalosporins • Vancomycin • Acyclovir • Glucocorticoids • Interferon • Acetylcholinesterase Inhibitors • Neuromuscular Blockers • Triptans & migraine • NSAIDs • Parkinsonism Drugs • Alzheimer\'s Disease Medications • Broad Spectrum Anti-Epileptics • Ethosuximide • Carbamazepine, phenytoin, gabapentin • Benzodiazepines, flumazenil • Barbiturates • IV Anaesthetics • Inhaled anesthetics, dantrolene • Opioids, naloxone, naltrexone • Nonbenzodiazepine hypnotics, melatonin, ramelteon • Armodafinil & Modafinil' },
        { system: 'Nervous System', subject: 'Pathophysiology', questions: 36, aulas: 'B&B: Cerebral and Lacunar Strokes • Vertebrobasilar Stroke Syndromes • Management of TIA/Stroke • Nerve Damage • Muscle Disorders • Neuromuscular Disorders • Headaches • Seizures • Spinal Cord Syndromes' },
        { system: 'Nervous System', subject: 'Microbiology', questions: 25, aulas: 'Sketchy Micro: Neisseria meningitidis • Streptococcus pneumoniae • Listeria monocytogenes • Haemophilus influenzae • Herpes simplex virus • Cryptococcus neoformans • Toxoplasma gondii • JC polyomavirus • Clostridium botulinum • Clostridium tetani' },
        { system: 'Nervous System', subject: 'Embryology', questions: 12, aulas: 'B&B: Neuroembryology • Neural Tube Defects' },
        { system: 'Nervous System', subject: 'Physiology', questions: 11, aulas: 'B&B: Nerve Damage • Blood Brain Barrier • Neurotransmitters • Autonomic Nervous System' },
        { system: 'Nervous System', subject: 'Biochemistry', questions: 9, aulas: 'B&B: Neurotransmitters | Dirty Medicine: Catecholamine Synthesis' },
        { system: 'Nervous System', subject: 'Genetics', questions: 8, aulas: 'B&B: Neural Tube Defects • Muscular Dystrophy' },
        { system: 'Nervous System', subject: 'Histology', questions: 4, aulas: 'B&B: Cells of the Nervous System' },
        { system: 'Nervous System', subject: 'Behavioral science', questions: 2, aulas: 'B&B: Delirium and Dementia • Sleep Disorders' },
        { system: 'Rheumatology/Orthopedics & Sports', subject: 'Anatomy', questions: 47, aulas: 'B&B: Knee • Shoulder and Elbow • Brachial Plexus • Wrist • Hand • Lumbosacral Plexus • Hip • Skeletal Muscle • Smooth Muscle • Bone • Connective Tissue • Cytoskeleton' },
        { system: 'Rheumatology/Orthopedics & Sports', subject: 'Pathology', questions: 46, aulas: 'B&B: Osteoarthritis • Gout • CPPD • Seronegative Spondyloarthritis • Rheumatoid Arthritis • Systemic Lupus Erythematosus • Scleroderma • Sjogren\'s Syndrome • Vasculitis • Bone Tumors • Bone Disorders | Pathoma: 2.4 Autoimmune Disorders Part 1 • 2.4 Autoimmune Disorders Part 2 • 3.1 Neoplasia' },
        { system: 'Rheumatology/Orthopedics & Sports', subject: 'Pharmacology', questions: 22, aulas: 'Sketchy Pharm: NSAIDs • Gout drugs • Glucocorticoids • TNF Inhibitors • Immunosuppressants • Bisphosphonates, raloxifene, denosumab, calcitonin • Teriparatide, vitamin D • Skeletal Muscle Relaxants' },
        { system: 'Rheumatology/Orthopedics & Sports', subject: 'Pathophysiology', questions: 20, aulas: 'B&B: Osteoarthritis • Gout • Rheumatoid Arthritis • Osteoporosis • Lumbar Radiculopathy' },
        { system: 'Rheumatology/Orthopedics & Sports', subject: 'Physiology', questions: 12, aulas: 'B&B: Skeletal Muscle • Smooth Muscle • Bone' },
        { system: 'Rheumatology/Orthopedics & Sports', subject: 'Biochemistry', questions: 6, aulas: 'Dirty Medicine: Collagen Synthesis' },
        { system: 'Rheumatology/Orthopedics & Sports', subject: 'Immunology', questions: 4, aulas: 'B&B: Systemic Lupus Erythematosus • Rheumatoid Arthritis • Vasculitis | Pathoma: 2.4 Autoimmune Disorders' },
        { system: 'Rheumatology/Orthopedics & Sports', subject: 'Microbiology', questions: 4, aulas: 'Sketchy Micro: Staphylococcus aureus • Neisseria gonorrhoeae • Salmonella' },
        { system: 'Rheumatology/Orthopedics & Sports', subject: 'Histology', questions: 2, aulas: 'B&B: Connective Tissue • Bone' },
        { system: 'Rheumatology/Orthopedics & Sports', subject: 'Embryology', questions: 1, aulas: 'B&B: Bone Disorders' },
        { system: 'Rheumatology/Orthopedics & Sports', subject: 'Genetics', questions: 1, aulas: 'B&B: Bone Disorders' },
        { system: 'Dermatology', subject: 'Pathology', questions: 57, aulas: 'B&B: Skin Disorders I • Skin Disorders II • Blistering Disorders • Skin Cancer • Neurocutaneous Disorders • Pigment Disorders • Vascular Lesions | Pathoma: 2.5 Wound Healing • 3.1 Neoplasia • 3.2 Carcinogenesis' },
        { system: 'Dermatology', subject: 'Microbiology', questions: 13, aulas: 'Sketchy Micro: Staphylococcus aureus • Streptococcus pyogenes • Dermatophytes • Candida albicans • Herpes simplex virus • Varicella-zoster virus • Human papillomavirus • HHV-8 Kaposi' },
        { system: 'Dermatology', subject: 'Pathophysiology', questions: 8, aulas: 'B&B: Hypersensitivity Disorders • Blistering Disorders' },
        { system: 'Dermatology', subject: 'Immunology', questions: 7, aulas: 'B&B: Hypersensitivity Disorders • Blistering Disorders' },
        { system: 'Dermatology', subject: 'Pharmacology', questions: 7, aulas: 'Sketchy Pharm: Glucocorticoids • Antihistamines • Penicillin • Vancomycin • Azoles • Terbinafine' },
        { system: 'Dermatology', subject: 'Histology', questions: 4, aulas: 'B&B: Skin • Epithelial Cells • Connective Tissue' },
        { system: 'Dermatology', subject: 'Biochemistry', questions: 1, aulas: 'Dirty Medicine: Collagen Synthesis' },
        { system: 'Dermatology', subject: 'Embryology', questions: 1, aulas: 'B&B: Neurocutaneous Disorders' },
        { system: 'Dermatology', subject: 'Genetics', questions: 1, aulas: 'B&B: Neurocutaneous Disorders' },
        { system: 'Pathology (General Principles)', subject: 'Pathology', questions: 36, aulas: 'B&B: Cellular Adaptations • Cell Injury • Free Radicals • Apoptosis • Necrosis • Inflammation Principles • Acute and Chronic Inflammation • Granulomatous Inflammation • Wound Healing and Scar • Pathologic Calcification • Neoplasia | Pathoma: 1.1 Growth Adaptations • 1.2 Cellular Injury • 1.3 Cell Death • 1.4 Free Radical Injury • 1.5 Amyloidosis • 2.1 Acute Inflammation Part 1 • 2.1 Acute Inflammation Part 2 • 2.1 Acute Inflammation Part 3 • 2.2 Chronic Inflammation • 2.5 Wound Healing • 3.1 Neoplasia • 3.2 Carcinogenesis Part 1 • 3.2 Carcinogenesis Part 2 • 3.2 Carcinogenesis Part 3 • 3.3 Tumor Progression • 3.4 Clinical Characteristics' },
        { system: 'Pathology (General Principles)', subject: 'Immunology', questions: 2, aulas: 'B&B: Inflammation Principles • Acute and Chronic Inflammation • Granulomatous Inflammation | Pathoma: 2.1 Acute Inflammation • 2.2 Chronic Inflammation' },
        { system: 'Pathology (General Principles)', subject: 'Pathophysiology', questions: 1, aulas: 'B&B: Cellular Adaptations • Cell Injury | Sketchy Pharm: NSAIDs • Glucocorticoids | Dirty Medicine: Arachidonic Acid Pathway' },
        { system: 'Hematology & Oncology', subject: 'Pathology', questions: 90, aulas: 'B&B: Hemolysis Basics • Extrinsic Hemolysis • Intrinsic Hemolysis • Microcytic Anemias • Thalassemias • Sickle Cell Anemia • Other Anemias • Porphyrias • Acute Leukemia • Chronic Leukemia • Hodgkin Lymphoma • Non-Hodgkin Lymphoma • Myeloproliferative Disorders • Plasma Cell Disorders • Amyloidosis | Pathoma: 1.5 Amyloidosis • 3.1 Neoplasia' },
        { system: 'Hematology & Oncology', subject: 'Pharmacology', questions: 42, aulas: 'Sketchy Pharm: Heparin, LMWH, fondaparinux • Warfarin • Antiplatelet agents • Thrombolytics • Methotrexate • Azathioprine, 6-mercaptopurine • Cyclophosphamide • Cisplatin • Bleomycin, doxorubicin • Etoposide • Vincristine, vinblastine, paclitaxel • Imatinib, erlotinib • Rituximab, trastuzumab' },
        { system: 'Hematology & Oncology', subject: 'Pathophysiology', questions: 41, aulas: 'B&B: Coagulation • Hypercoagulable States • Coagulopathies • Platelet Disorders • Hemolysis Basics' },
        { system: 'Hematology & Oncology', subject: 'Biochemistry', questions: 26, aulas: 'B&B: Porphyrias | Dirty Medicine: Heme Synthesis Pathway' },
        { system: 'Hematology & Oncology', subject: 'Immunology', questions: 10, aulas: 'B&B: Plasma Cell Disorders | Pathoma: 1.5 Amyloidosis' },
        { system: 'Hematology & Oncology', subject: 'Physiology', questions: 9, aulas: 'B&B: Coagulation • Platelet Activation • Hemolysis Basics • Blood Groups' },
        { system: 'Hematology & Oncology', subject: 'Genetics', questions: 7, aulas: 'B&B: Thalassemias • Sickle Cell Anemia' },
        { system: 'Hematology & Oncology', subject: 'Microbiology', questions: 3, aulas: 'Sketchy Micro: Plasmodium • Babesia • Epstein-Barr virus • HTLV-1' },
        { system: 'Hematology & Oncology', subject: 'Biostatistics', questions: 1, aulas: 'B&B: Clinical Trials' },
        { system: 'Allergy & Immunology', subject: 'Immunology', questions: 79, aulas: 'B&B: Hypersensitivity • Innate Immunology • T-Cells • B-Cells • The Complement System • Lymph Nodes and Spleen • Immune Deficiency Syndromes • Transplants • Systemic Lupus Erythematosus • Rheumatoid Arthritis • Scleroderma • Sjogren\'s Syndrome | Pathoma: 2.3 Primary Immunodeficiency • 2.4 Autoimmune Disorders Part 1 • 2.4 Autoimmune Disorders Part 2' },
        { system: 'Allergy & Immunology', subject: 'Pathophysiology', questions: 11, aulas: 'B&B: Hypersensitivity • Systemic Lupus Erythematosus' },
        { system: 'Allergy & Immunology', subject: 'Pharmacology', questions: 11, aulas: 'Sketchy Pharm: Antihistamines • Sympathomimetics • Glucocorticoids • Immunosuppressants • TNF Inhibitors • Azathioprine, 6-mercaptopurine, mycophenolate' },
        { system: 'Allergy & Immunology', subject: 'Pathology', questions: 6, aulas: 'B&B: Systemic Lupus Erythematosus • Rheumatoid Arthritis | Pathoma: 2.4 Autoimmune Disorders' },
        { system: 'Allergy & Immunology', subject: 'Microbiology', questions: 1, aulas: 'B&B: Immune Deficiency Syndromes' },
        { system: 'Microbiology (General Principles)', subject: 'Microbiology', questions: 30, aulas: 'B&B: Bacteria • Shapes and Strains • Bacterial Culture • Special Growth Requirements • Virulence • Growth and Genetics • Bacterial Identification • Staphylococci • Streptococci • Other Gram Positives • Gram Negative Rods • Other Gram Negatives • Spirochetes • Zoonotic Infections • Mycobacteria • Fungal Pneumonias • Fungal Skin Infections • Opportunistic Fungal Infections • Malaria • Protozoa • Helminths • Virus Structure • DNA Viruses • Herpes Viruses • RNA Viruses | Sketchy Micro: (all relevant organisms)' },
        { system: 'Infectious Diseases', subject: 'Microbiology', questions: 191, aulas: 'B&B: Staphylococci • Streptococci • Gram Negative Rods • Spirochetes • Mycobacteria • Meningitis • Pneumonia • Urinary Tract Infections • Fungal Pneumonias • Fungal Skin Infections • Opportunistic Fungal Infections • HIV • Malaria • Protozoa • Helminths • DNA Viruses • Herpes Viruses • RNA Viruses • Viral Hepatitis | Sketchy Micro: (all organisms by system)' },
        { system: 'Infectious Diseases', subject: 'Pharmacology', questions: 50, aulas: 'B&B: Penicillins • Beta Lactams • Sulfonamides • Protein Synthesis Inhibitors • Other Antibiotics • Antifungal Drugs • HIV Drugs • Antiviral Drugs | Sketchy Pharm: Penicillin • Nafcillin, Oxacillin • Ampicillin, Amoxicillin, Piperacillin • Cephalosporins • Monobactams & Carbapenems • Vancomycin • Daptomycin • Tetracyclines • Macrolides • Clindamycin • Aminoglycosides • Trimethoprim/sulfamethoxazole • Fluoroquinolones • Metronidazole • Amphotericin, flucytosine • Azoles • Griseofulvin, Terbinafine, Echinocandins • NRTIs • NNRTIs • Protease inhibitors • Maraviroc, fusion inhibitors, integrase inhibitors • Acyclovir, valacyclovir • Ganciclovir, foscarnet, cidofovir' },
        { system: 'Infectious Diseases', subject: 'Immunology', questions: 14, aulas: 'B&B: HIV • Immune Deficiency Syndromes' },
        { system: 'Infectious Diseases', subject: 'Pathology', questions: 10, aulas: 'B&B: Pneumonia • Meningitis' },
        { system: 'Infectious Diseases', subject: 'Pathophysiology', questions: 4, aulas: 'B&B: HIV' },
        { system: 'Infectious Diseases', subject: 'Genetics', questions: 1, aulas: 'B&B: HIV' },
        { system: 'Infectious Diseases', subject: 'Histology', questions: 1, aulas: 'B&B: Bacteria' },
        { system: 'Biochemistry (General Principles)', subject: 'Biochemistry', questions: 64, aulas: 'B&B: Amino Acids • Phenylalanine and Tyrosine • Other Amino Acids • Ammonia • Glucose • Glycolysis • Gluconeogenesis • Glycogen • HMP Shunt • Fructose and Galactose • Pyruvate Dehydrogenase • TCA Cycle • Electron Transport Chain • Exercise and Starvation • Inborn Errors of Metabolism • DNA Structure • DNA Replication • DNA Mutations • DNA Repair • Transcription • Translation • PCR • Blotting • Flow Cytometry • ELISA • Microarrays and FISH • Cell Cycle • Cell Structure • Cytoskeleton • Fatty Acids • Ketone Bodies • Lipid Metabolism | Dirty Medicine: Amino Acids • Urea Cycle • Catecholamine Synthesis • Collagen Synthesis • Glycolysis • Pyruvate Pathways & Metabolism • HMP Shunt • TCA/Citric Acid Cycle • Electron Transport Chain • Gluconeogenesis • Glycogen Storage Diseases • Galactose Metabolism • Fructose Metabolism • Metabolic Fuel & Starvation • Cell Biology - Organelles • Signal Transduction Pathways • Lipid Transport • Fatty Acid Synthesis • Familial Dyslipidemias • Ketone Body Synthesis • Fatty Acid (Beta) Oxidation' },
        { system: 'Biochemistry (General Principles)', subject: 'Genetics', questions: 1, aulas: 'B&B: DNA Structure • DNA Mutations' },
        { system: 'Genetics (General Principles)', subject: 'Genetics', questions: 58, aulas: 'B&B: Genetic Principles • Pedigrees • Down Syndrome • Trisomy Disorders • Muscular Dystrophy • Trinucleotide Repeat Disorders • Deletion Syndromes • Turner and Klinefelter Syndromes • DNA Structure • Purine Metabolism • Pyrimidine Metabolism • DNA Replication • DNA Mutations • DNA Repair • Transcription • Imprinting • Translation | Dirty Medicine: Trinucleotide Repeats • X-Linked Pedigrees • Purine Synthesis • Pyrimidine Synthesis • Purine Salvage Pathway • Collagen Synthesis' },
        { system: 'Genetics (General Principles)', subject: 'Biochemistry', questions: 3, aulas: 'B&B: Purine Metabolism • Pyrimidine Metabolism | Dirty Medicine: Purine Synthesis • Pyrimidine Synthesis • Purine Salvage Pathway' },
        { system: 'Biostatistics & Epidemiology', subject: 'Biostatistics', questions: 118, aulas: 'B&B: Study Designs • Risk Quantification • Bias • Clinical Trials • Evidence-Based Medicine • Public Health • Statistics • Sensitivity and Specificity • Predictive Values • Diagnostic Tests • Hypothesis Testing • Tests of Significance • Correlations | Randy Neil: Biostatistics - The Basics • Biostatistics SUMMARY • Prevention, Box, Logic • Bias & Confounding • Case Control & Cohort • Population Pyramids • Effect Size • Cumulative Probability • Effect Modulation vs Confounding • Drug Ads, Abstract • Kaplan-Meier Curve' },
        { system: 'Biostatistics & Epidemiology', subject: 'Genetics', questions: 2, aulas: 'B&B: Study Designs' },
        { system: 'Pharmacology (General Principles)', subject: 'Pharmacology', questions: 44, aulas: 'B&B: Enzymes • Enzyme Inhibitors • Dose-Response • Pharmacokinetics • Drug Elimination | Sketchy Pharm: Introduction to CYP450 Enzymes • P-Glycoprotein & Enterohepatic Recycling • Agonists, Antagonists & Allosteric Modulators • Pharmacodynamic & Pharmacokinetic Drug Interactions • Plasma Concentration & Therapeutic Range • Oral Drug Absorption & Bioavailability • Drug Distribution & Protein Binding • Volume of Distribution • Clearance & Area Under the Curve • Elimination-Rate Constant, Half-Life & Steady State | Dirty Medicine: Signal Transduction Pathways' },
        { system: 'Pharmacology (General Principles)', subject: 'Immunology', questions: 1, aulas: 'B&B: Dose-Response' },
        { system: 'Poisoning & Environmental Exposure', subject: 'Pharmacology', questions: 21, aulas: 'B&B: Ethanol Metabolism | Sketchy Pharm: Opioids, naloxone, naltrexone | Dirty Medicine: Alcohol Metabolism • High Yield Alcohol' },
        { system: 'Poisoning & Environmental Exposure', subject: 'Pathophysiology', questions: 4, aulas: 'Pathoma: 1.4 Free Radical Injury | Dirty Medicine: Glutathione Pathways' },
        { system: 'Poisoning & Environmental Exposure', subject: 'Biochemistry', questions: 3, aulas: 'B&B: Ethanol Metabolism | Pathoma: 1.4 Free Radical Injury | Dirty Medicine: Alcohol Metabolism • High Yield Alcohol • Glutathione Pathways' },
        { system: 'Poisoning & Environmental Exposure', subject: 'Pathology', questions: 2, aulas: 'Pathoma: 1.4 Free Radical Injury' },
        { system: 'Poisoning & Environmental Exposure', subject: 'Physiology', questions: 2, aulas: 'Dirty Medicine: Glutathione Pathways' },
        { system: 'Ear, Nose & Throat (ENT)', subject: 'Anatomy', questions: 15, aulas: 'B&B: Auditory System • Vestibular System • Pharyngeal Arches • Cleft Lip and Palate • Pharyngeal Pouches and Clefts' },
        { system: 'Ear, Nose & Throat (ENT)', subject: 'Pathophysiology', questions: 6, aulas: 'B&B: Auditory System • Vestibular System' },
        { system: 'Ear, Nose & Throat (ENT)', subject: 'Embryology', questions: 5, aulas: 'B&B: Pharyngeal Arches • Cleft Lip and Palate • Pharyngeal Pouches and Clefts' },
        { system: 'Ear, Nose & Throat (ENT)', subject: 'Pathology', questions: 5, aulas: 'B&B: Auditory System • Vestibular System' },
        { system: 'Ear, Nose & Throat (ENT)', subject: 'Microbiology', questions: 4, aulas: 'Sketchy Micro: Streptococcus pyogenes • Haemophilus influenzae • Moraxella' },
        { system: 'Ear, Nose & Throat (ENT)', subject: 'Pharmacology', questions: 2, aulas: 'Sketchy Pharm: Antihistamines' },
        { system: 'Ear, Nose & Throat (ENT)', subject: 'Genetics', questions: 1, aulas: 'B&B: Cleft Lip and Palate' },
        { system: 'Ear, Nose & Throat (ENT)', subject: 'Immunology', questions: 1, aulas: 'B&B: Auditory System' },
        { system: 'Ear, Nose & Throat (ENT)', subject: 'Physiology', questions: 1, aulas: 'B&B: Auditory System • Vestibular System' },
        { system: 'Ophthalmology', subject: 'Pharmacology', questions: 9, aulas: 'Sketchy Pharm: Cholinomimetics • Muscarinic antagonists • Beta blockers • Acetazolamide, mannitol' },
        { system: 'Ophthalmology', subject: 'Pathophysiology', questions: 6, aulas: 'B&B: The Pupil • The Lens • The Retina • Gaze Palsies • Glaucoma' },
        { system: 'Ophthalmology', subject: 'Anatomy', questions: 5, aulas: 'B&B: The Pupil • The Lens • The Retina • Eye Movements • Visual Fields' },
        { system: 'Ophthalmology', subject: 'Pathology', questions: 5, aulas: 'B&B: Structural Eye Disorders • Glaucoma' },
        { system: 'Ophthalmology', subject: 'Microbiology', questions: 3, aulas: 'Sketchy Micro: Chlamydia trachomatis • Neisseria gonorrhoeae • Herpes simplex virus • Cytomegalovirus' },
        { system: 'Ophthalmology', subject: 'Immunology', questions: 1, aulas: 'B&B: Structural Eye Disorders' },
        { system: 'Ophthalmology', subject: 'Physiology', questions: 1, aulas: 'B&B: The Pupil • The Lens • The Retina • Eye Movements • Visual Fields' },
        { system: 'Miscellaneous (Multisystem)', subject: 'Pathology', questions: 5, aulas: 'Pathoma: 3.1 Neoplasia' },
        { system: 'Miscellaneous (Multisystem)', subject: 'Genetics', questions: 4, aulas: 'B&B: Genetic Principles' },
        { system: 'Miscellaneous (Multisystem)', subject: 'Embryology', questions: 3, aulas: 'B&B: Embryonic Genes • Embryogenesis • Germ Layers • Errors in Morphogenesis • Teratogens I • Teratogens II' },
        { system: 'Miscellaneous (Multisystem)', subject: 'Pathophysiology', questions: 3, aulas: 'Pathoma: 1.2 Cellular Injury' },
        { system: 'Miscellaneous (Multisystem)', subject: 'Physiology', questions: 3, aulas: 'B&B: (varies by topic)' },
        { system: 'Miscellaneous (Multisystem)', subject: 'Anatomy', questions: 2, aulas: 'B&B: (varies by topic)' },
        { system: 'Miscellaneous (Multisystem)', subject: 'Pharmacology', questions: 2, aulas: 'Sketchy Pharm: (varies by topic)' },
        { system: 'Miscellaneous (Multisystem)', subject: 'Biochemistry', questions: 1, aulas: 'Dirty Medicine: (varies by topic)' },
        { system: 'Miscellaneous (Multisystem)', subject: 'Immunology', questions: 1, aulas: 'B&B: (varies by topic)' }
    ];

    // O gerador de cronograma le uma tabela separada por TAB, nesta ordem:
    // System, Subject/Category, Questions, Data de Inicio, Data de Fim,
    // Aulas Recomendadas, concluido. Datas em branco: quem preenche e o gerador.
    function comoTabela() {
        return PADRAO.map(function (i) {
            return [i.system, i.subject, i.questions, '', '', i.aulas, 'FALSE'].join('\t');
        }).join('\n');
    }

    function totalDeQuestoes() {
        return PADRAO.reduce(function (n, i) { return n + i.questions; }, 0);
    }

    window.WardCronograma = {
        PADRAO: PADRAO,
        comoTabela: comoTabela,
        totalDeQuestoes: totalDeQuestoes
    };
})();
