-- ============================================
-- SAMPLE QUESTIONS FOR TESTING WASA-1
-- 100 questions with simple content for testing
-- ============================================

-- First, make sure WASA-1 exists and get its ID
-- The setup SQL should have created it with id=1

-- Insert 100 sample questions
INSERT INTO self_assessment_questions (self_assessment_id, question_number, question_tags, question, choices, correct_answer, explanation)
VALUES
-- Block 1: Questions 1-50
(1, 1, 'Anatomy::Cardiovascular::Gross Anatomy', 'Heart', '["A. Alpha", "B. Beta", "C. Gamma", "D. Delta", "E. Epsilon"]', 'B', 'Correct answer is B'),
(1, 2, 'Anatomy::Respiratory::Gross Anatomy', 'Lungs', '["A. Alpha", "B. Beta", "C. Gamma", "D. Delta", "E. Epsilon"]', 'C', 'Correct answer is C'),
(1, 3, 'Anatomy::Gastrointestinal::Gross Anatomy', 'Stomach', '["A. Alpha", "B. Beta", "C. Gamma", "D. Delta", "E. Epsilon"]', 'A', 'Correct answer is A'),
(1, 4, 'Anatomy::Nervous::Gross Anatomy', 'Brain', '["A. Alpha", "B. Beta", "C. Gamma", "D. Delta", "E. Epsilon"]', 'D', 'Correct answer is D'),
(1, 5, 'Anatomy::Musculoskeletal::Gross Anatomy', 'Bone', '["A. Alpha", "B. Beta", "C. Gamma", "D. Delta", "E. Epsilon"]', 'E', 'Correct answer is E'),
(1, 6, 'Physiology::Cardiovascular::Cardiac', 'Contraction', '["A. Alpha", "B. Beta", "C. Gamma", "D. Delta", "E. Epsilon"]', 'B', 'Correct answer is B'),
(1, 7, 'Physiology::Respiratory::Ventilation', 'Breathing', '["A. Alpha", "B. Beta", "C. Gamma", "D. Delta", "E. Epsilon"]', 'A', 'Correct answer is A'),
(1, 8, 'Physiology::Renal::Filtration', 'Kidney', '["A. Alpha", "B. Beta", "C. Gamma", "D. Delta", "E. Epsilon"]', 'C', 'Correct answer is C'),
(1, 9, 'Physiology::Endocrine::Hormones', 'Insulin', '["A. Alpha", "B. Beta", "C. Gamma", "D. Delta", "E. Epsilon"]', 'D', 'Correct answer is D'),
(1, 10, 'Physiology::Nervous::Neurotransmitters', 'Dopamine', '["A. Alpha", "B. Beta", "C. Gamma", "D. Delta", "E. Epsilon"]', 'E', 'Correct answer is E'),
(1, 11, 'Biochemistry::Metabolism::Glycolysis', 'Glucose', '["A. Alpha", "B. Beta", "C. Gamma", "D. Delta", "E. Epsilon"]', 'A', 'Correct answer is A'),
(1, 12, 'Biochemistry::Metabolism::Krebs', 'Citrate', '["A. Alpha", "B. Beta", "C. Gamma", "D. Delta", "E. Epsilon"]', 'B', 'Correct answer is B'),
(1, 13, 'Biochemistry::Genetics::DNA', 'Replication', '["A. Alpha", "B. Beta", "C. Gamma", "D. Delta", "E. Epsilon"]', 'C', 'Correct answer is C'),
(1, 14, 'Biochemistry::Genetics::RNA', 'Transcription', '["A. Alpha", "B. Beta", "C. Gamma", "D. Delta", "E. Epsilon"]', 'D', 'Correct answer is D'),
(1, 15, 'Biochemistry::Proteins::Synthesis', 'Translation', '["A. Alpha", "B. Beta", "C. Gamma", "D. Delta", "E. Epsilon"]', 'E', 'Correct answer is E'),
(1, 16, 'Pathology::Cardiovascular::Ischemia', 'Infarction', '["A. Alpha", "B. Beta", "C. Gamma", "D. Delta", "E. Epsilon"]', 'A', 'Correct answer is A'),
(1, 17, 'Pathology::Respiratory::Pneumonia', 'Infection', '["A. Alpha", "B. Beta", "C. Gamma", "D. Delta", "E. Epsilon"]', 'B', 'Correct answer is B'),
(1, 18, 'Pathology::Gastrointestinal::Ulcer', 'Erosion', '["A. Alpha", "B. Beta", "C. Gamma", "D. Delta", "E. Epsilon"]', 'C', 'Correct answer is C'),
(1, 19, 'Pathology::Renal::Nephritis', 'Inflammation', '["A. Alpha", "B. Beta", "C. Gamma", "D. Delta", "E. Epsilon"]', 'D', 'Correct answer is D'),
(1, 20, 'Pathology::Nervous::Stroke', 'Hemorrhage', '["A. Alpha", "B. Beta", "C. Gamma", "D. Delta", "E. Epsilon"]', 'E', 'Correct answer is E'),
(1, 21, 'Pharmacology::Cardiovascular::Antihypertensives', 'Lisinopril', '["A. Alpha", "B. Beta", "C. Gamma", "D. Delta", "E. Epsilon"]', 'A', 'Correct answer is A'),
(1, 22, 'Pharmacology::Cardiovascular::Antiarrhythmics', 'Amiodarone', '["A. Alpha", "B. Beta", "C. Gamma", "D. Delta", "E. Epsilon"]', 'B', 'Correct answer is B'),
(1, 23, 'Pharmacology::Respiratory::Bronchodilators', 'Albuterol', '["A. Alpha", "B. Beta", "C. Gamma", "D. Delta", "E. Epsilon"]', 'C', 'Correct answer is C'),
(1, 24, 'Pharmacology::Endocrine::Antidiabetics', 'Metformin', '["A. Alpha", "B. Beta", "C. Gamma", "D. Delta", "E. Epsilon"]', 'D', 'Correct answer is D'),
(1, 25, 'Pharmacology::Nervous::Analgesics', 'Morphine', '["A. Alpha", "B. Beta", "C. Gamma", "D. Delta", "E. Epsilon"]', 'E', 'Correct answer is E'),
(1, 26, 'Microbiology::Bacteria::Gram Positive', 'Staphylococcus', '["A. Alpha", "B. Beta", "C. Gamma", "D. Delta", "E. Epsilon"]', 'A', 'Correct answer is A'),
(1, 27, 'Microbiology::Bacteria::Gram Negative', 'Escherichia', '["A. Alpha", "B. Beta", "C. Gamma", "D. Delta", "E. Epsilon"]', 'B', 'Correct answer is B'),
(1, 28, 'Microbiology::Viruses::DNA Viruses', 'Herpes', '["A. Alpha", "B. Beta", "C. Gamma", "D. Delta", "E. Epsilon"]', 'C', 'Correct answer is C'),
(1, 29, 'Microbiology::Viruses::RNA Viruses', 'Influenza', '["A. Alpha", "B. Beta", "C. Gamma", "D. Delta", "E. Epsilon"]', 'D', 'Correct answer is D'),
(1, 30, 'Microbiology::Fungi::Yeasts', 'Candida', '["A. Alpha", "B. Beta", "C. Gamma", "D. Delta", "E. Epsilon"]', 'E', 'Correct answer is E'),
(1, 31, 'Immunology::Innate::Complement', 'Activation', '["A. Alpha", "B. Beta", "C. Gamma", "D. Delta", "E. Epsilon"]', 'A', 'Correct answer is A'),
(1, 32, 'Immunology::Adaptive::Humoral', 'Antibodies', '["A. Alpha", "B. Beta", "C. Gamma", "D. Delta", "E. Epsilon"]', 'B', 'Correct answer is B'),
(1, 33, 'Immunology::Adaptive::Cellular', 'Tcells', '["A. Alpha", "B. Beta", "C. Gamma", "D. Delta", "E. Epsilon"]', 'C', 'Correct answer is C'),
(1, 34, 'Immunology::Hypersensitivity::Type I', 'Anaphylaxis', '["A. Alpha", "B. Beta", "C. Gamma", "D. Delta", "E. Epsilon"]', 'D', 'Correct answer is D'),
(1, 35, 'Immunology::Autoimmune::Lupus', 'SLE', '["A. Alpha", "B. Beta", "C. Gamma", "D. Delta", "E. Epsilon"]', 'E', 'Correct answer is E'),
(1, 36, 'Anatomy::Cardiovascular::Histology', 'Myocardium', '["A. Alpha", "B. Beta", "C. Gamma", "D. Delta", "E. Epsilon"]', 'A', 'Correct answer is A'),
(1, 37, 'Anatomy::Respiratory::Histology', 'Alveoli', '["A. Alpha", "B. Beta", "C. Gamma", "D. Delta", "E. Epsilon"]', 'B', 'Correct answer is B'),
(1, 38, 'Anatomy::Gastrointestinal::Histology', 'Villi', '["A. Alpha", "B. Beta", "C. Gamma", "D. Delta", "E. Epsilon"]', 'C', 'Correct answer is C'),
(1, 39, 'Anatomy::Renal::Histology', 'Nephron', '["A. Alpha", "B. Beta", "C. Gamma", "D. Delta", "E. Epsilon"]', 'D', 'Correct answer is D'),
(1, 40, 'Anatomy::Endocrine::Histology', 'Islets', '["A. Alpha", "B. Beta", "C. Gamma", "D. Delta", "E. Epsilon"]', 'E', 'Correct answer is E'),
(1, 41, 'Physiology::Cardiovascular::Hemodynamics', 'Pressure', '["A. Alpha", "B. Beta", "C. Gamma", "D. Delta", "E. Epsilon"]', 'A', 'Correct answer is A'),
(1, 42, 'Physiology::Respiratory::Gas Exchange', 'Diffusion', '["A. Alpha", "B. Beta", "C. Gamma", "D. Delta", "E. Epsilon"]', 'B', 'Correct answer is B'),
(1, 43, 'Physiology::Gastrointestinal::Digestion', 'Absorption', '["A. Alpha", "B. Beta", "C. Gamma", "D. Delta", "E. Epsilon"]', 'C', 'Correct answer is C'),
(1, 44, 'Physiology::Renal::Secretion', 'Excretion', '["A. Alpha", "B. Beta", "C. Gamma", "D. Delta", "E. Epsilon"]', 'D', 'Correct answer is D'),
(1, 45, 'Physiology::Endocrine::Feedback', 'Regulation', '["A. Alpha", "B. Beta", "C. Gamma", "D. Delta", "E. Epsilon"]', 'E', 'Correct answer is E'),
(1, 46, 'Biochemistry::Lipids::Cholesterol', 'Synthesis', '["A. Alpha", "B. Beta", "C. Gamma", "D. Delta", "E. Epsilon"]', 'A', 'Correct answer is A'),
(1, 47, 'Biochemistry::Vitamins::Fat Soluble', 'ADEK', '["A. Alpha", "B. Beta", "C. Gamma", "D. Delta", "E. Epsilon"]', 'B', 'Correct answer is B'),
(1, 48, 'Biochemistry::Vitamins::Water Soluble', 'BC', '["A. Alpha", "B. Beta", "C. Gamma", "D. Delta", "E. Epsilon"]', 'C', 'Correct answer is C'),
(1, 49, 'Biochemistry::Enzymes::Kinetics', 'Michaelis', '["A. Alpha", "B. Beta", "C. Gamma", "D. Delta", "E. Epsilon"]', 'D', 'Correct answer is D'),
(1, 50, 'Biochemistry::Enzymes::Inhibition', 'Competitive', '["A. Alpha", "B. Beta", "C. Gamma", "D. Delta", "E. Epsilon"]', 'E', 'Correct answer is E'),

-- Block 2: Questions 51-100
(1, 51, 'Pathology::Cardiovascular::Heart Failure', 'Congestion', '["A. Alpha", "B. Beta", "C. Gamma", "D. Delta", "E. Epsilon"]', 'A', 'Correct answer is A'),
(1, 52, 'Pathology::Respiratory::COPD', 'Emphysema', '["A. Alpha", "B. Beta", "C. Gamma", "D. Delta", "E. Epsilon"]', 'B', 'Correct answer is B'),
(1, 53, 'Pathology::Gastrointestinal::Cirrhosis', 'Fibrosis', '["A. Alpha", "B. Beta", "C. Gamma", "D. Delta", "E. Epsilon"]', 'C', 'Correct answer is C'),
(1, 54, 'Pathology::Renal::CKD', 'Failure', '["A. Alpha", "B. Beta", "C. Gamma", "D. Delta", "E. Epsilon"]', 'D', 'Correct answer is D'),
(1, 55, 'Pathology::Endocrine::Diabetes', 'Hyperglycemia', '["A. Alpha", "B. Beta", "C. Gamma", "D. Delta", "E. Epsilon"]', 'E', 'Correct answer is E'),
(1, 56, 'Pharmacology::Antibiotics::Penicillins', 'Amoxicillin', '["A. Alpha", "B. Beta", "C. Gamma", "D. Delta", "E. Epsilon"]', 'A', 'Correct answer is A'),
(1, 57, 'Pharmacology::Antibiotics::Cephalosporins', 'Ceftriaxone', '["A. Alpha", "B. Beta", "C. Gamma", "D. Delta", "E. Epsilon"]', 'B', 'Correct answer is B'),
(1, 58, 'Pharmacology::Antibiotics::Fluoroquinolones', 'Ciprofloxacin', '["A. Alpha", "B. Beta", "C. Gamma", "D. Delta", "E. Epsilon"]', 'C', 'Correct answer is C'),
(1, 59, 'Pharmacology::Antivirals::HIV', 'Tenofovir', '["A. Alpha", "B. Beta", "C. Gamma", "D. Delta", "E. Epsilon"]', 'D', 'Correct answer is D'),
(1, 60, 'Pharmacology::Antifungals::Azoles', 'Fluconazole', '["A. Alpha", "B. Beta", "C. Gamma", "D. Delta", "E. Epsilon"]', 'E', 'Correct answer is E'),
(1, 61, 'Microbiology::Parasites::Protozoa', 'Plasmodium', '["A. Alpha", "B. Beta", "C. Gamma", "D. Delta", "E. Epsilon"]', 'A', 'Correct answer is A'),
(1, 62, 'Microbiology::Parasites::Helminths', 'Ascaris', '["A. Alpha", "B. Beta", "C. Gamma", "D. Delta", "E. Epsilon"]', 'B', 'Correct answer is B'),
(1, 63, 'Microbiology::Prions::TSE', 'CJD', '["A. Alpha", "B. Beta", "C. Gamma", "D. Delta", "E. Epsilon"]', 'C', 'Correct answer is C'),
(1, 64, 'Microbiology::Bacteria::Spirochetes', 'Treponema', '["A. Alpha", "B. Beta", "C. Gamma", "D. Delta", "E. Epsilon"]', 'D', 'Correct answer is D'),
(1, 65, 'Microbiology::Bacteria::Mycobacteria', 'Tuberculosis', '["A. Alpha", "B. Beta", "C. Gamma", "D. Delta", "E. Epsilon"]', 'E', 'Correct answer is E'),
(1, 66, 'Immunology::Transplant::Rejection', 'Acute', '["A. Alpha", "B. Beta", "C. Gamma", "D. Delta", "E. Epsilon"]', 'A', 'Correct answer is A'),
(1, 67, 'Immunology::Immunodeficiency::Primary', 'SCID', '["A. Alpha", "B. Beta", "C. Gamma", "D. Delta", "E. Epsilon"]', 'B', 'Correct answer is B'),
(1, 68, 'Immunology::Immunodeficiency::Secondary', 'AIDS', '["A. Alpha", "B. Beta", "C. Gamma", "D. Delta", "E. Epsilon"]', 'C', 'Correct answer is C'),
(1, 69, 'Immunology::Vaccines::Active', 'Immunization', '["A. Alpha", "B. Beta", "C. Gamma", "D. Delta", "E. Epsilon"]', 'D', 'Correct answer is D'),
(1, 70, 'Immunology::Vaccines::Passive', 'Immunoglobulin', '["A. Alpha", "B. Beta", "C. Gamma", "D. Delta", "E. Epsilon"]', 'E', 'Correct answer is E'),
(1, 71, 'Anatomy::Nervous::Cranial Nerves', 'Vagus', '["A. Alpha", "B. Beta", "C. Gamma", "D. Delta", "E. Epsilon"]', 'A', 'Correct answer is A'),
(1, 72, 'Anatomy::Nervous::Spinal Cord', 'Tracts', '["A. Alpha", "B. Beta", "C. Gamma", "D. Delta", "E. Epsilon"]', 'B', 'Correct answer is B'),
(1, 73, 'Anatomy::Musculoskeletal::Joints', 'Synovial', '["A. Alpha", "B. Beta", "C. Gamma", "D. Delta", "E. Epsilon"]', 'C', 'Correct answer is C'),
(1, 74, 'Anatomy::Musculoskeletal::Muscles', 'Skeletal', '["A. Alpha", "B. Beta", "C. Gamma", "D. Delta", "E. Epsilon"]', 'D', 'Correct answer is D'),
(1, 75, 'Anatomy::Reproductive::Male', 'Testes', '["A. Alpha", "B. Beta", "C. Gamma", "D. Delta", "E. Epsilon"]', 'E', 'Correct answer is E'),
(1, 76, 'Physiology::Nervous::Action Potential', 'Depolarization', '["A. Alpha", "B. Beta", "C. Gamma", "D. Delta", "E. Epsilon"]', 'A', 'Correct answer is A'),
(1, 77, 'Physiology::Musculoskeletal::Contraction', 'Actin', '["A. Alpha", "B. Beta", "C. Gamma", "D. Delta", "E. Epsilon"]', 'B', 'Correct answer is B'),
(1, 78, 'Physiology::Reproductive::Hormones', 'Estrogen', '["A. Alpha", "B. Beta", "C. Gamma", "D. Delta", "E. Epsilon"]', 'C', 'Correct answer is C'),
(1, 79, 'Physiology::Hematology::Coagulation', 'Cascade', '["A. Alpha", "B. Beta", "C. Gamma", "D. Delta", "E. Epsilon"]', 'D', 'Correct answer is D'),
(1, 80, 'Physiology::Hematology::Hemoglobin', 'Oxygen', '["A. Alpha", "B. Beta", "C. Gamma", "D. Delta", "E. Epsilon"]', 'E', 'Correct answer is E'),
(1, 81, 'Pathology::Hematology::Anemia', 'Deficiency', '["A. Alpha", "B. Beta", "C. Gamma", "D. Delta", "E. Epsilon"]', 'A', 'Correct answer is A'),
(1, 82, 'Pathology::Hematology::Leukemia', 'Malignancy', '["A. Alpha", "B. Beta", "C. Gamma", "D. Delta", "E. Epsilon"]', 'B', 'Correct answer is B'),
(1, 83, 'Pathology::Oncology::Breast', 'Carcinoma', '["A. Alpha", "B. Beta", "C. Gamma", "D. Delta", "E. Epsilon"]', 'C', 'Correct answer is C'),
(1, 84, 'Pathology::Oncology::Lung', 'Adenocarcinoma', '["A. Alpha", "B. Beta", "C. Gamma", "D. Delta", "E. Epsilon"]', 'D', 'Correct answer is D'),
(1, 85, 'Pathology::Oncology::Colon', 'Polyps', '["A. Alpha", "B. Beta", "C. Gamma", "D. Delta", "E. Epsilon"]', 'E', 'Correct answer is E'),
(1, 86, 'Pharmacology::Oncology::Chemotherapy', 'Cytotoxic', '["A. Alpha", "B. Beta", "C. Gamma", "D. Delta", "E. Epsilon"]', 'A', 'Correct answer is A'),
(1, 87, 'Pharmacology::Psychiatry::Antidepressants', 'SSRI', '["A. Alpha", "B. Beta", "C. Gamma", "D. Delta", "E. Epsilon"]', 'B', 'Correct answer is B'),
(1, 88, 'Pharmacology::Psychiatry::Antipsychotics', 'Haloperidol', '["A. Alpha", "B. Beta", "C. Gamma", "D. Delta", "E. Epsilon"]', 'C', 'Correct answer is C'),
(1, 89, 'Pharmacology::Psychiatry::Anxiolytics', 'Benzodiazepines', '["A. Alpha", "B. Beta", "C. Gamma", "D. Delta", "E. Epsilon"]', 'D', 'Correct answer is D'),
(1, 90, 'Pharmacology::Neurology::Antiepileptics', 'Valproate', '["A. Alpha", "B. Beta", "C. Gamma", "D. Delta", "E. Epsilon"]', 'E', 'Correct answer is E'),
(1, 91, 'Behavioral::Ethics::Autonomy', 'Consent', '["A. Alpha", "B. Beta", "C. Gamma", "D. Delta", "E. Epsilon"]', 'A', 'Correct answer is A'),
(1, 92, 'Behavioral::Ethics::Beneficence', 'Good', '["A. Alpha", "B. Beta", "C. Gamma", "D. Delta", "E. Epsilon"]', 'B', 'Correct answer is B'),
(1, 93, 'Behavioral::Ethics::Non-maleficence', 'Harm', '["A. Alpha", "B. Beta", "C. Gamma", "D. Delta", "E. Epsilon"]', 'C', 'Correct answer is C'),
(1, 94, 'Behavioral::Ethics::Justice', 'Fairness', '["A. Alpha", "B. Beta", "C. Gamma", "D. Delta", "E. Epsilon"]', 'D', 'Correct answer is D'),
(1, 95, 'Behavioral::Communication::Breaking Bad News', 'SPIKES', '["A. Alpha", "B. Beta", "C. Gamma", "D. Delta", "E. Epsilon"]', 'E', 'Correct answer is E'),
(1, 96, 'Biostatistics::Study Design::RCT', 'Randomization', '["A. Alpha", "B. Beta", "C. Gamma", "D. Delta", "E. Epsilon"]', 'A', 'Correct answer is A'),
(1, 97, 'Biostatistics::Study Design::Cohort', 'Prospective', '["A. Alpha", "B. Beta", "C. Gamma", "D. Delta", "E. Epsilon"]', 'B', 'Correct answer is B'),
(1, 98, 'Biostatistics::Statistics::Sensitivity', 'TruePositive', '["A. Alpha", "B. Beta", "C. Gamma", "D. Delta", "E. Epsilon"]', 'C', 'Correct answer is C'),
(1, 99, 'Biostatistics::Statistics::Specificity', 'TrueNegative', '["A. Alpha", "B. Beta", "C. Gamma", "D. Delta", "E. Epsilon"]', 'D', 'Correct answer is D'),
(1, 100, 'Biostatistics::Statistics::PPV', 'Prevalence', '["A. Alpha", "B. Beta", "C. Gamma", "D. Delta", "E. Epsilon"]', 'E', 'Correct answer is E')
ON CONFLICT (self_assessment_id, question_number) DO NOTHING;

-- Update the total_questions count in self_assessments
UPDATE self_assessments SET total_questions = 100 WHERE code = 'WASA-1';
